import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import { Menu } from '@/componentes/Menu'

export default function Home() {
  return (
    <>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossOrigin="anonymous"/>
      </Head>
      <Menu/>
      <main className={styles.main}>
        <div className='container text-black'>
          <h1 className={styles.title}>Página Inicial</h1>
        </div>
      </main>
    </>
  )
}
